### ISSUE TITLE
HTTP Error 407: Proxy Authorization Required

### ISSUE THREAD

**Issue by chrisbuckmaster** [Geolicious/OSMroute#13]
Hi

I receive a python error when trying to run a route between two points. It appears as though it is an issue with proxy authorisation but I have my proxy details in the QGIS options set up and I am able to access and download plugins from the repositories so I do not know what else I might need to check for this to work? Please see my python error below.

```
2016-11-02T11:10:05	1	Traceback (most recent call last):
			  File "C:/Users/chris.buckmaster/.qgis2/python/plugins\OSMroute\OSMroute.py", line 237, in run
			    response_start=urllib2.urlopen(req).read()
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 127, in urlopen
			    return _opener.open(url, data, timeout)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 410, in open
			    response = meth(req, response)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 523, in http_response
			    'http', request, response, code, msg, hdrs)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 448, in error
			    return self._call_chain(*args)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 382, in _call_chain
			    result = func(*args)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 531, in http_error_default
			    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
			HTTPError: HTTP Error 407: Proxy Authorization Required
```

**Comment by riccardoklinger** [comment]
Hi @cartochris .
thank for mentioning this issue. First question: which QGis Version are you running and second which OSMroute plugin version are you running on? It seems like 2.18 when it comes to QGIS, right?

**Comment by chrisbuckmaster** [comment]
Hi @riccardoklinger - yes I am running QGIS 2.18 and it looks like I have version 0.6 of OSM route.

**Comment by riccardoklinger** [comment]
Well, to be honest with you: 2.18 is still not stable. I'll close this issue for now and wait for 2.18 come up as stable. If you're able to try this with 2.16.1 I would appreciate it.
For 2.18 it might be an error from withing QGIS itself and it will be hard for me to solve this.

**Comment by chrisbuckmaster** [comment]
@riccardoklinger I just tried it in QGIS 2.16.3 and seem to get the same error message
