### ISSUE TITLE
OSM route - Python error, troubles with accessibility.

### ISSUE THREAD

**Issue by sonka93** [Geolicious/OSMroute#17]
Hallo,
I've got a problem with OSM route plugin, it does not work. There's a problem with Python. I'm totally begginer so I've got no idea what happened. Here's the code of error:

2017-05-18T21:15:09	1	Traceback (most recent call last):
			  File "C:/Users/Sonia/.qgis2/python/plugins\OSMroute\OSMroute.py", line 237, in run
			    response_start=urllib2.urlopen(req).read()
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 127, in urlopen
			    return _opener.open(url, data, timeout)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 404, in open
			    response = self._open(req, data)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 422, in _open
			    '_open', req)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 382, in _call_chain
			    result = func(*args)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 1214, in http_open
			    return self.do_open(httplib.HTTPConnection, req)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\urllib2.py", line 1184, in do_open
			    raise URLError(err)
			URLError: <urlopen error [Errno 10061] Nie mo�na nawi�za� po��czenia, poniewa� komputer docelowy aktywnie go odmawia>

The last sentence is in polisch, so I translate: 
URLError: <urlopen error [Errno 10061] You can not to make a connection because the target computer is actively refusing to connect >

Please, help!

**Comment by riccardoklinger** [comment]
Please use the plugins OSM tools from Nils Nolde and not OSM route. The API
has changed my plugin is not working anymore.
If you need professional support, contact me again!

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

telefon: 030 - 3982021 33
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by sonka93** [comment]
Thank you very much, you saved my master thesis ;)
